[mypy]
python_version = 3.8
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = False
warn_return_any = True
warn_unused_ignores = True

[mypy-plots.*]
ignore_missing_imports = True

[mypy-flask_limiter.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-plotly.*]
ignore_missing_imports = True
